# language: haskell

# See http://www.reddit.com/r/haskell/comments/1os3f6/how_to_use_travisci_with_multiple_ghc_versions/

env:
 - GHCVER=7.6.3
 - GHCVER=7.8.4
 - GHCVER=7.10.2

matrix:
  allow_failures:
   - env: GHCVER=7.10.1

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install cabal-install-1.22 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH

install:
 - cabal-1.22 update
 - cabal-1.22 install happy
 - cabal-1.22 install alex
 - cabal-1.22 install --only-dependencies --enable-tests;

script:
 - cabal-1.22 configure --enable-tests
 - cabal-1.22 build
 - dist/build/test-language-javascript/test-language-javascript
 - cabal-1.22 check
 - cabal-1.22 haddock
 - cabal-1.22 sdist
